### ISSUE TITLE
still could not shut down or reset，even i the version 3.0.

### ISSUE THREAD

**Issue by lomoer** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#10]
i update efi to v3.0，but i found i couldnt shut down the laptop.i plug a usb wifi adapter ，does it matter？

**Comment by lomoer** [comment]
btw，i have two solid hard drive，one nvme one sata.

**Comment by lomoer** [comment]
i have solved the problem,it’s about the bios.the older bios A02 doesn’t work well.when  update it to A05，i goes perfectly

**Comment by johnnynunez** [comment]
For hackintosh, it is always advisable to have the latest BIOS

**Comment by daydaychen** [comment]
Does your camera work properly?

**Comment by Koohoko** [comment]
> i have solved the problem,it’s about the bios.the older bios A02 doesn’t work well.when update it to A05，i goes perfectly

Hi @lomoer , would you kindly share the a05 bios with me? I am facing the same issue here. Thanks so much!
