### ISSUE TITLE
I2C Bus Device

### ISSUE THREAD

**Issue by webfalter** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#12]
The right button on the touchpad is not working properly.
Do you have this result too?
Is it possible that one of the other ssdt influences this function?

ASPI patches GFX0 and so on are no longer needed with WEG.

**Comment by johnnynunez** [comment]
thanks! You can configure on .plist on voodooi2c or voodooi2csynaptic

**Comment by webfalter** [comment]
Which value is responsible (Right Button) ?

**Comment by johnnynunez** [comment]
I don't know, ask here https://gitter.im/alexandred/VoodooI2C

**Comment by webfalter** [comment]
A pity, thought you know the answer
In Alexandred's right button, only when interacting with your EFI is not.
I had patched the DSDT, but without multitouch but with the right button.
Since I do not need to ask for grid.

**Comment by webfalter** [comment]
Command back ... The behavior is of course an Apple and you use Ctrl
