### ISSUE TITLE
Bios PWM xiaomi air 12.5

### ISSUE THREAD

**Issue by ghost** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#14]
Hi, thanks for this project. It is working great. Everything is working perfectly but I have a problem with the flickering at half brightness caused by PWM. I modded the vbios to set PWM to 2000hz but I can’t write the full bios with fptw...can you help me with that? I am on bios A5, xiaomi air 12.5 6y30.

**Comment by johnnynunez** [comment]
You need a flash programmer. I bought one on banggod but you can fix this with rmcf

**Comment by johnnynunez** [comment]
I have the solution and i will post next days

**Comment by ghost** [comment]
Why is it possible to flash the Xiaomi Air 13 bios without programmer and the air 12.5 is not?
I’ve already tried changing the PWMMax in RMCF but the flicker worsened, unfortunately :/

**Comment by johnnynunez** [comment]
only on xiaomi notebook pro is possible and air 13 first gen

**Comment by ghost** [comment]
I tried your last commit and it partially worked. I changed LMAX to 0xD2 and flicker is completely gone. Thank you :)

**Comment by ghost** [comment]
I was wrong, it is gone when brightness is set at 10%, but perceivable when brightness is set within 20-70%

**Comment by johnnynunez** [comment]
on skylake it is 0x56c :(

**Comment by johnnynunez** [comment]
@overnightmare95 At the moment I do not have a flicker on the screen
