### ISSUE TITLE
Whatevergreen 1.3.1

### ISSUE THREAD

**Issue by webfalter** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#15]
Hello,
how does your XiaoMI behave if you use the not yet released version of WEG https://github.com/acidanthera/WhateverGreen/blob/master/Changelog.md ? 
Can you boot or does that end in a KP?

Thank you

**Comment by johnnynunez** [comment]
I have windows now and I'm on vacation. In september, I will return to macOS Catalina

**Comment by webfalter** [comment]
Has also done the guys from Acidanthera, have found the bug and fixed
