### ISSUE TITLE
HDMI Issue

### ISSUE THREAD

**Issue by ahuppp** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#16]
Hi Johnnync13,

Thanks for your excelllent Hackintosh work!
Most things are working fine. However the HDMI is not working under Mojave.
Any ideas ?

**Comment by johnnynunez** [comment]
@ahuppp https://github.com/johnnync13/EFI-Xiaomi-Notebook-air-12-5/releases/tag/v4.4
