### ISSUE TITLE
How to transfer for 7y30 Mi Air 12.5? 

### ISSUE THREAD

**Issue by igor211-cmd** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#20]
Hey man, is there a way to use your EFI for the 12.5 with the m3 7y30 CPU?
The original by influenzer is outdated, but your work is great and always up2date!

Thanks!

**Comment by francescobabbaro** [comment]
I agree! I've the 7y30, and with some small changes (CPUDataProvider.kext, GPU info in devices/properties, SMBios MacBook 10,1) this EFI works very well on our PC! But I'm not sure it's fully compatible. 
@johnnync13 , can you kindly tell me what are the SSDTs, kexts etc intended for 6y30 only? So I could try to modify them. Thanks!

**Comment by johnnynunez** [comment]
@francescobabbaro 
@igor211-cmd 
I use this tutorials 
To he most important to start: 
Kexts: https://www.tonymacx86.com/threads/guide-installing-3rd-party-kexts-el-capitan-sierra-high-sierra-mojave-catalina.268964/
Lilu and his plugins: https://www.tonymacx86.com/threads/an-idiots-guide-to-lilu-and-its-plug-ins.260063/
fix iMessage: https://www.tonymacx86.com/threads/how-to-fix-imessage.110471/
fix with DSDT https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/
fix with hotpaches https://www.tonymacx86.com/threads/guide-using-clover-to-hotpatch-acpi.200137/page-54
and the first files : https://github.com/RehabMan/OS-X-Clover-Laptop-Config
OC: https://github.com/daliansky/OC-little
Clover: https://github.com/daliansky/P-little
Fix IGPU: https://www.tonymacx86.com/threads/guide-intel-framebuffer-patching-using-whatevergreen.256490/
to fix USB: https://www.tonymacx86.com/threads/the-new-beginners-guide-to-usb-port-configuration.286553/
And now is more easy with Hackintool. There are a lot of tutorials
And the majority of kexts is:
https://github.com/acidanthera
https://github.com/alexandred/VoodooI2C

And I use Xcode to build them or this script: https://github.com/corpnewt/Lilu-and-Friends
to fix hidpi https://github.com/xzhih/one-key-hidpi
to fix cpu https://github.com/stevezhengshiqi/one-key-cpufriend

And I use mod bios to unlock cfg lock and more: use this tutorial of the open core
https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf
and this page https://www.win-raid.com

If you are developer, and you like this world, you should to learn Xcode and reverse engineering to create kexts

**Comment by francescobabbaro** [comment]
> @francescobabbaro
> @igor211-cmd
> I use this tutorials
> To he most important to start:
> Kexts: https://www.tonymacx86.com/threads/guide-installing-3rd-party-kexts-el-capitan-sierra-high-sierra-mojave-catalina.268964/
> Lilu and his plugins: https://www.tonymacx86.com/threads/an-idiots-guide-to-lilu-and-its-plug-ins.260063/
> fix iMessage: https://www.tonymacx86.com/threads/how-to-fix-imessage.110471/
> fix with DSDT https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/
> fix with hotpaches https://www.tonymacx86.com/threads/guide-using-clover-to-hotpatch-acpi.200137/page-54
> and the first files : https://github.com/RehabMan/OS-X-Clover-Laptop-Config
> OC: https://github.com/daliansky/OC-little
> Clover: https://github.com/daliansky/P-little
> Fix IGPU: https://www.tonymacx86.com/threads/guide-intel-framebuffer-patching-using-whatevergreen.256490/
> to fix USB: https://www.tonymacx86.com/threads/the-new-beginners-guide-to-usb-port-configuration.286553/
> And now is more easy with Hackintool. There are a lot of tutorials
> And the majority of kexts is:
> https://github.com/acidanthera
> https://github.com/alexandred/VoodooI2C
> 
> And I use Xcode to build them or this script: https://github.com/corpnewt/Lilu-and-Friends
> to fix hidpi https://github.com/xzhih/one-key-hidpi
> to fix cpu https://github.com/stevezhengshiqi/one-key-cpufriend
> 
> And I use mod bios to unlock cfg lock and more: use this tutorial of the open core
> https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf
> and this page https://www.win-raid.com
> 
> If you are developer, and you like this world, you should to learn Xcode and reverse engineering to create kexts

Thanks for your kindness! Last question: can you tell me which SSDTs and kexts (according to you, a general answer will be appreciated, too) are CPU/GPU related? I'm a student like you (computer engineering, but not programming addicted, honestly...) and I could try to make compatible your very good EFI. Thanks again!

**Comment by johnnynunez** [comment]
https://github.com/johnnync13/Mi-NB-Gaming-Laptop-MacOS.git
@francescobabbaro @igor211-cmd @Koohoko try this!
Send me message on telegram https://t.me/HackingtoshXiaomi
