### ISSUE TITLE
Problems with switching to OC boot

### ISSUE THREAD

**Issue by daydaychen** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#22]
1. switching to OC EFI and restart hackintosh, 
2. reset NVRAM in OC
3. start hackintosh
4. get stuck in a big apple logo......

What do I need to do?

**Comment by daydaychen** [comment]
Intel WIFI is working???!!!

**Comment by johnnynunez** [comment]
@daydaychen yeah! but at the moment is only for a gated community. I will upload soon. Now, I'm seeing is stable or not
For me OpenCore works fine!

**Comment by daydaychen** [comment]
Thanks, looking forward to your good news!
