### ISSUE TITLE
Bios TR100A09.zip

### ISSUE THREAD

**Issue by webfalter** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#23]
Have you already done the BIOS TR100A09 update yourself on the Xiaomi? Does that work on the 12 "model? Do you have a source?

**Comment by johnnynunez** [comment]
Yes! I have A09 bios

**Comment by webfalter** [comment]
Can you please take a picture of the first page of the Bios FN F2 and upload it here? Thank you

EDIT
Thanks, I just installed it

Do you have any idea whether you can change the bios like the pro?
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/BIOS

**Comment by johnnynunez** [comment]
@webfalter I could do this but not have a lot time...
