### ISSUE TITLE
Eternal logo when loading from a flash drive

### ISSUE THREAD

**Issue by MarshalX** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#24]
Created a bootable flash drive via https://github.com/corpnewt/gibMacOS. It uses opencore 0.5.5. Could this be a problem? 061-44387 - 10.15.3 macOS Catalina. Created a flash drive through the utility, replaced the contents of the BOOT and OS folders from the EFIOS folder. Thanks!

**Comment by MarshalX** [comment]
CPU: M3-**7**Y30

**Comment by MarshalX** [comment]
About BIOS from repo
![изображение](https://user-images.githubusercontent.com/15520314/75075043-06310380-550e-11ea-83f0-04b059cd842d.png)

**Comment by MarshalX** [comment]
As I understand it, you do not support a laptop with a 7th generation processor. It turns out that it waits for news from the influenist. He accepted the pull request, but of course it doesn’t work ...

**Comment by johnnynunez** [comment]
contact with @influenist
