### ISSUE TITLE
Latest version trackpad and keyboard are not driven

### ISSUE THREAD

**Issue by daydaychen** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#27]
OC and Clover have the same problem. CFG Unlocked。

**Comment by johnnynunez** [comment]
@daydaychen for me works well
https://github.com/johnnync13/EFI-Xiaomi-Notebook-air-12-5/releases/tag/v6.4.2

**Comment by daydaychen** [comment]
@johnnync13 thank for replying, I try again.

**Comment by johnnynunez** [comment]
@daydaychen tell something soon!

**Comment by daydaychen** [comment]
@johnnync13 works well, Thanks!
