### ISSUE TITLE
Touchpad does not work

### ISSUE THREAD

**Issue by lsdlh** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#28]
The latest version of efi,oc mode，Tried 10.15.4, 10.15.3, 10.14.6, all have problems，Excuse me, which version fits best？air12.5

**Comment by lsdlh** [comment]
After installing mac，When booting from a solid state drive，Must use your efi?Is the eif folder on usb OK?I replaced  SSD with your efi folder, unlocked the CFG，The touchpad is ready to use。EFI on previously used USB,Cfg not unlocked,The touchpad doesn't work，Unknown reason，mac version 15.3，bios version A09，OpenCore used，efi version is 6.42

**Comment by johnnynunez** [comment]
if you have cfg unlocked, you should remove these parameters on kernel in OC
<img width="312" alt="Screenshot 2020-04-01 at 12 44 04" src="https://user-images.githubusercontent.com/22727137/78128629-83f20400-7416-11ea-9885-7eaa47530680.png">
