### ISSUE TITLE
No bootable Device

### ISSUE THREAD

**Issue by marcofarolfi** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#29]
Hi!
I created my macOS Catalina USB install media with MacBook Air (Catalina) from terminal and i mounted EFI partition but it's empty (is it normal?). 
I copied contents of EFI in a USB 2 device and EFIOC in a USB 3 device. My Mi air's bios is updated to TR100A09.zip and secure boot is disabled. 
Unfortunately when i plug my usb devices in my Mi air and i press power button it shows me that there aren't bootable device.
What'd I do wrong?

Thanks :)

**Comment by johnnynunez** [comment]
@marcofarolfi you are creating usb wrong. If you don't know, you should create with unibeast
