### ISSUE TITLE
eternal logo at the beginning

### ISSUE THREAD

**Issue by handsomebroB** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#31]
i have the same laptop with 6y30 but can not boot up with the a09 bios, opencore, stuck after select the installer disk ,just a eternal white apple there! could u help!

**Comment by handsomebroB** [comment]
the same with clover, stuck at the white apple, but smaller.

**Comment by handsomebroB** [comment]
did i need to do some setup in bios?

**Comment by lsdlh** [comment]
解锁cfg或者把 AppleCpuPmCfgLock  AppleXcpmCfgLock这两个打钩

**Comment by handsomebroB** [comment]
> 解锁cfg或者把 AppleCpuPmCfgLock AppleXcpmCfgLock这两个打钩

thanks man, it worked!

**Comment by johnnynunez** [comment]
@handsomebroB you have to modify BIOS. It is better performance

**Comment by ghost** [comment]
> 解锁cfg或者把 AppleCpuPmCfgLock AppleXcpmCfgLock这两个打钩

老哥，能不能甩个解锁CFG的链接，不会解啊

**Comment by lsdlh** [comment]
他那个github不是出教程了吗，按照那个就行，还有图片https://github.com/johnnync13/EFI-Xiaomi-Notebook-air-12-5/blob/master/BIOS/XiaomiValues.png




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "songzhelun333"<notifications@github.com&gt;; 
发送时间: 2020年6月28日(星期天) 晚上6:59
收件人: "johnnync13/EFI-Xiaomi-Notebook-air-12-5"<EFI-Xiaomi-Notebook-air-12-5@noreply.github.com&gt;; 
抄送: "1763221541"<1763221541@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [johnnync13/EFI-Xiaomi-Notebook-air-12-5] eternal logo at the beginning (#31)





  
解锁cfg或者把 AppleCpuPmCfgLock AppleXcpmCfgLock这两个打钩
  
老哥，能不能甩个解锁CFG的链接，不会解啊
