### ISSUE TITLE
Touchpad and Bluetooth don't work

### ISSUE THREAD

**Issue by lsdlh** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#32]
On macOS Mojave 10.14.6,Touchpad and Bluetooth don't work,oc mode,Power-on prompt OCS:no schema for shrinkmemorymap at 12 index,No problem on macOS Catalina,May I ask what is the reason?

**Comment by johnnynunez** [comment]
I don't know... I'm on 10.15.4.
Schema is possible that opencore is still in beta

**Comment by lsdlh** [comment]
On 10.15.4,After turning on hidpi,After the screen wakes up,It's only a quarter size, Will flash,Do you have this situation?

**Comment by johnnynunez** [comment]
@lsdlh I use https://github.com/xzhih/one-key-hidpi
and then I change default resolution in system preferences

**Comment by lsdlh** [comment]
thank you
