### ISSUE TITLE
Mod Grub Shell

### ISSUE THREAD

**Issue by handsomebroB** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#34]
when i trying to modify the bios, after select partition Mod Grub Shell, nothing happened,what should i do? thanks

**Comment by johnnynunez** [comment]
for me works well. You have to write the command like readme with values of BIOS folder image

**Comment by handsomebroB** [comment]
> for me works well. You have to write the command like readme with values of BIOS folder image

i mean i cant open the tools...

**Comment by johnnynunez** [comment]
Well I do not know. As I said before, it works well for me. When you are in the boot, you give the space key and it will open the partitions hidden among them the shell

**Comment by handsomebroB** [comment]
> Well I do not know. As I said before, it works well for me. When you are in the boot, you give the space key and it will open the partitions hidden among them the shell

ok, thanks anyway

**Comment by marcofarolfi** [comment]
> 
> 
> > for me works well. You have to write the command like readme with values of BIOS folder image
> 
> i mean i cant open the tools...

Just download modGRUBShell.efi from here https://github.com/datasone/grub-mod-setup_var/releases, and copy it in EFI/OC/Tools. It worked for me :)
