### ISSUE TITLE
I 've totally follow the instructions but it dosen't work.

### ISSUE THREAD

**Issue by Gary-zzy** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#39]
Every time I select to install mac os ,the white Apple logo will appears for just few seconds and then my computer will reboot.I am wondering if my bios is too old(A04).Should I update it into 0906?  Thanks a lot for your help...:)

**Comment by daydaychen** [comment]
> Every time I select to install mac os ,the white Apple logo will appears for just few seconds and then my computer will reboot.I am wondering if my bios is too old(A04).Should I update it into 0906?  Thanks a lot for your help...:)

yes

**Comment by Gary-zzy** [comment]
Thanks!!!

**Comment by Gary-zzy** [comment]
so you mean that I just use the bios in this package?I am not sure caz this file says that         " **IMPORTANT: Thes scripts only work on the Xiaomi Mi Notebook air 13,3" 2018 Model (TM1703)**"       
:(

**Comment by johnnynunez** [comment]
yo have to do manually with open shell modified

**Comment by Gary-zzy** [comment]
> yo have to do manually with open shell modified

so you mean I just follow the steps in the file?

**Comment by johnnynunez** [comment]
what not work for you?

**Comment by Gary-zzy** [comment]
> what not work for you?

thanks !!!!!!I have successfullly finished updating A04 into A09 ,but I still have the same problem as my first comment. Could you help me?

**Comment by johnnynunez** [comment]
Now you have to modify bios, with mod shell

**Comment by Gary-zzy** [comment]
> Now you have to modify bios, with mod shell
:)there are just three options after I click space: windos  macos base system and reset NVRAM.I suppose Mob grub shell dosen't exist.

**Comment by johnnynunez** [comment]
in my version efi exists, is mod grub shell

**Comment by Gary-zzy** [comment]
> 

i used 7.5.1

**Comment by johnnynunez** [comment]
![B41D980D-5BFC-4CFF-BC6A-F665B3713B1D](https://user-images.githubusercontent.com/22727137/83619397-1be1aa80-a58c-11ea-8edd-da81b3fd4524.png)
For me too

**Comment by johnnynunez** [comment]
But v7.5.1 is not versión on this post. What laptop are you talking?

**Comment by Gary-zzy** [comment]
Xiaomi Notebook Air 2016 12.5"
![IMG_20200603_212911](https://user-images.githubusercontent.com/58905046/83642539-8cff7d00-a5e1-11ea-86f9-1ac10ad9bd1f.jpg)

**Comment by Koohoko** [comment]
> Xiaomi Notebook Air 2016 12.5"
> ![IMG_20200603_212911](https://user-images.githubusercontent.com/58905046/83642539-8cff7d00-a5e1-11ea-86f9-1ac10ad9bd1f.jpg)

I think you have to press the space key

**Comment by johnnynunez** [comment]
V7.5.1 is on Xiaomi mi air i7-8550u not for here 😅

**Comment by Gary-zzy** [comment]
I see ....but where can I get the proper EFI, I've download it from your instruction:"Making the USB stick Xiaomi compatible:

Download the latest version of the EFI folder from **here**"

**Comment by Gary-zzy** [comment]
thanks,I've done:)

**Comment by johnnynunez** [comment]
ah it is possible that the link is not changed for my Xiaomi mi air repository
