### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by AdamNguyen1** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#4]
I'm new and I don't have much knowledge on hackintosh. I installed high sierra already using your EFI. I used Unibeast. I have a pretty bad problem with everything flickering. Can you give me a set of instructions to properly install this?

**Comment by ykla** [comment]
In fact, after  sleep my screen will ficker also and no sound.

**Comment by AdamNguyen1** [comment]
Youtube is just flickering all the time, videos are unplayable, Spotify too. I feel like I installed it wrong, or like I'm missing something after I fully install.

**Comment by johnnynunez** [comment]
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/

**Comment by johnnynunez** [comment]
if you are using 10.14 it's normal. It is a beta EFI and with high sierra you have to use release version

**Comment by johnnynunez** [comment]
Instructions:
Yo need a HUB type C or USB and external mouse. Install macOS. Copy folder to Drive. Generate new smbios with clover configurator and write uuidgen in terminal some times, and copy one.
Reboot.
Pass sudo kextcache -i or kext utility.
Reboot.
Now trackpad works and facetime, imessage...
