### ISSUE TITLE
Internet issue

### ISSUE THREAD

**Issue by Gary-zzy** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#40]
I can not access Internet neither using usb to network port nor using usb internet sharing in the phone.It says  "an internet connection is required to install macos ", How can I access to the Internet . I wonder wether my usb port is broken.Thank you for your generous help。

**Comment by johnnynunez** [comment]
the gibmacos requires internet connection, so you have to create usb with other macos or with virtual machine

**Comment by Gary-zzy** [comment]
> the gibmacos requires internet connection, so you have to create usb with other macos or with virtual machine

sry, I mean I am already in the install interface but I cannot install it caz there is no Internet though I use something like that :
![Screenshot_2020-06-05-23-15-06-650_com taobao tao](https://user-images.githubusercontent.com/58905046/83893700-de933d80-a782-11ea-8a9f-569730c3ea12.jpg)
