### ISSUE TITLE
Install doesn't work with neither OC or Clover 

### ISSUE THREAD

**Issue by giandonatoFarina** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#41]
I tried to execute installation in verbose mode to detect where it stopped: there are some errors at the beginning of the installation. I'm using latest release (6.7.6 at current date).

**Comment by johnnynunez** [comment]
@gFarinaGit do you do mod bios?

**Comment by giandonatoFarina** [comment]
I'm using the bios version that is in this repository

**Comment by marcofarolfi** [comment]
I have problems with 6.7.6. I suggest you use 6.7.5 and if you haven't unlocked the bios with Mod Grub Shell yet, just edit the config.plist file and select AppleCpuPmCfgLock and AppleXcpmCfgLock. It should work
