### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by Gary-zzy** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#42]
There is no sound though I can change the volume.

**Comment by johnnynunez** [comment]
I have sound

**Comment by daydaychen** [comment]
> There is no sound though I can change the volume.

Me too, The sound card is not recognized.

**Comment by johnnynunez** [comment]
<img width="719" alt="Captura de pantalla 2020-06-13 a las 17 06 44" src="https://user-images.githubusercontent.com/22727137/84572129-4c012880-ad98-11ea-937b-cd466b4a64c2.png">
<img width="722" alt="Captura de pantalla 2020-06-13 a las 17 06 38" src="https://user-images.githubusercontent.com/22727137/84572130-4d325580-ad98-11ea-9230-4aa7099c6eee.png">

**Comment by daydaychen** [comment]
Thanks！Caused by wrong BIOS parameters.

**Comment by webfalter** [comment]
@daydaychen What are these bios settings?

**Comment by daydaychen** [comment]
> @daydaychen What are these bios settings?

https://github.com/johnnync13/EFI-Xiaomi-Notebook-air-12-5/blob/master/BIOS/XiaomiValues.png
