### ISSUE TITLE
i can't install it

### ISSUE THREAD

**Issue by p4c0ga** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#44]
I need help ... I have been trying to install a hackintosh for a 12.5-inch Mi notebook Air with the m3-6y30 processor for several days. I have followed the guide, but after hundreds of attempts I cannot install it. The problem lies in the installation medium ... after creating hundreds of USB with different EFIs it never lets me install. It does not go beyond the Apple logo, sometimes it loads the bar and then a prohibited disc appears, (both with clover and with opencore) I am desperate, could you help me?
I already installed another one in my pro notebook that is going great

**Comment by p4c0ga** [comment]
Please

**Comment by savvadesogle** [comment]
Hello. I have the same problem. 
BIOS A09, Xiaomi mi air 12.5 m3-6y30.
EFI 6.8.1, 6.7.5, 6.7.9
My steps:
1. Download MacOS 10.15.6 (gibMacOS, 001-36735 - 10.15.6 macOS Catalina) or another like 10.14.x, 10.13.x
2. MakeInstall -> keys (1 or 1OG or 1G)
3. F2 -> UEFI
4. Booting to Flash drive.
"_It does not go beyond the Apple logo, sometimes it loads the bar_"  - ~70% and reboot.

**Comment by the-eric-kwok** [comment]
I can successfully install Catalina on 12.5 m3-6y30. But not Big Sur. Big Sur PB1 stuck at apfs formatting, don't know why.
Before installation, I unchecked almost all kexts but Lilu, VirtualSMC and its plugins, WhateverGreen.
Also, **AppleCpuPmCfgLock** and **AppleXcpmCfgLock** should be checked if you didn't flash your BIOS or etc.
Add a `-v` (verbose) before your boot-args for debugging, and do a ResetNVRAM to make it apply.

**Comment by Rayhom** [comment]
@p4c0ga, halo, you installed  MAC OS into your MI PRO with internet online?

**Comment by masstes** [comment]
I have the same issue.
