### ISSUE TITLE
trackpad don't working with gestures

### ISSUE THREAD

**Issue by boardman21** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#46]
i am using the newest efi folder and everything is working except for bt and trackpad with gestures

can anyone help me?

**Comment by the-eric-kwok** [comment]
This works for me
Remember to modify config.plist and load VoodooInput from VoodooI2C/Contents/Plugins/ instead of VoodooPS2Controller
[Archive.zip](https://github.com/johnnync13/EFI-Xiaomi-Notebook-air-12-5/files/5065085/Archive.zip)

**Comment by the-eric-kwok** [comment]
This bundle is in beta and I believe it will be release soon.
See [#364](https://github.com/VoodooI2C/VoodooI2C/issues/364)
