### ISSUE TITLE
It seems that no sound and cannot adjust light by Fn+F4/F5

### ISSUE THREAD

**Issue by ykla** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#5]
on MAC 10.14.1
It seems that no sound and cannot adjust light by Fn+F4/F5 on my xiaomi notebook.

**Comment by johnnynunez** [comment]
I have sound and keys works fine

**Comment by webfalter** [comment]
_It seems that cannot adjust light by Fn+F4/F5 on my xiaomi notebook._

Sry
is now working in OC after I changed the plist
