### ISSUE TITLE
EFI Big Sur Work

### ISSUE THREAD

**Issue by giusedm** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#52]
@johnnync13 @pparrilla 
This EFI work with Big Sur https://github.com/giusedm/Xiaomi_Air_12.5_EFI_O.C
Touchpad work like mouse and don't have gestures

**Comment by johnnynunez** [comment]
thank you @giusedm I fix it now!

**Comment by giusedm** [comment]
https://github.com/giusedm/Xiaomi_Air_12.5_EFI_O.C/releases

>

**Comment by giusedm** [comment]
https://github.com/giusedm/Xiaomi_Air_12.5_EFI_O.C/releases/tag/1.0
