### ISSUE TITLE
No sound here ... ALC235 with layout-id at 18 ?

### ISSUE THREAD

**Issue by alucardxs** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#57]
Hi dude,

First, thanks for your hard work, it works well under BigSur (I've got the Core m3 version from Mibook air 12.5 2016).
But I do not have any sound ... I checked your layout-id in the boot parameters and it's 18 ... weird as the ALC235 does not support this codec, is it normal ? Btw the way, I checked every supported codecs for this sound card with no success ...

https://github.com/acidanthera/AppleALC/wiki/Supported-codecs
ALC235 : layout 3, 11, 12, 14, 15, 16, 21, 22, 28

Thanks for your answer 👍

**Comment by alucardxs** [comment]
I tried with 28 and it works now.

**Comment by ykla** [comment]
Does your WiFi works？

**Comment by alucardxs** [comment]
> Does your WiFi works？

Yes; it works greats using AirportItwm.kext

**Comment by ykla** [comment]
Could you please give me one EFI？Thanks a lot.

**Comment by ykla** [comment]
I changed It but stopped at an Apple logo. And I set debug=0x100 -v

**Comment by HtetWaiAung** [comment]
> > Does your WiFi works？
> 
> Yes; it works greats using AirportItwm.kext

Can you give me that wifi kext? mine is not working.

**Comment by alucardxs** [comment]
You should download kext from here : 

https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.1.0

Use this one on Big Sur : AirportItlwm_v1.0_Beta_BigSur.kext.zip

**Comment by giusedm** [comment]
try if it works with my EFI https://github.com/giusedm/Xiaomi_Air_12.5_EFI_O.C

**Comment by HtetWaiAung** [comment]
I am on Catalina. Now working with Airportlwm.
On BigSur, Everything work fine?

**Comment by alucardxs** [comment]
> I am on Catalina. Now working with Airportlwm.
> On BigSur, Everything work fine?

Yep !

**Comment by giusedm** [comment]
if you try the efi wich I linked, you see wich work all

**Comment by giusedm** [comment]
https://github.com/giusedm/Xiaomi_Air_12.5_EFI_O.C
