### ISSUE TITLE
Audio and wifi not work on BIG sur

### ISSUE THREAD

**Issue by ykla** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#59]
Thanks at first, But Audio and wifi not work on BIG sur

**Comment by alucardxs** [comment]
You should type in boot-arguments : layout-id=28 for the audio issue.
And about the Wifi problem, download AirportItlwm.kext put the file in the kext folder and in the config.plist file.

Both are working great.

**Comment by ykla** [comment]
sorry but where to add boot-arguments : layout-id=28 ？

**Comment by sibintb** [comment]
Downloaded airportltlwm.kext, and placed in kext folder, how to add it in the config.plist?

**Comment by alucardxs** [comment]
https://dortania.github.io/OpenCore-Install-Guide/ktext.html#wifi-and-bluetooth

**Comment by giusedm** [comment]
try if it works with my EFI https://github.com/giusedm/Xiaomi_Air_12.5_EFI_O.C

**Comment by ykla** [comment]
@giusedm Both of them also not work.

**Comment by giusedm** [comment]
the model of your laptop is Xiaomi notebook 12,5 m3-6?

**Comment by ykla** [comment]
@giusedm Of course sure. I am xiaomi 12.5 air 6Y30. No airportltlwm.kext in your kext, how does wifi work ?

**Comment by giusedm** [comment]
if you go to look in the repo of my profile you will be able to see that the wifi kext is there. And it is also added in the config. Everything works for me

**Comment by ykla** [comment]
@giusedm I mix EFI files, sorry, all woks now. Thanks a lot.
