### ISSUE TITLE
No drag and drop

### ISSUE THREAD

**Issue by kyall** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#6]
first of all, thank you so much for your work!

Everything is working perfectly with one small problem:
The touchpad does not drag and drop.

Any ideas?

**Comment by ykla** [comment]
It's works on my notebook.

**Comment by zhiyuanzmj** [comment]
My computer will shut down automatically after half an hour, and The system Settings I did before will be initialized.
please help me,I'm a Chinese.

**Comment by diggerdu** [comment]
@zhiyuanzmj 可能是电池接口松了

**Comment by zhiyuanzmj** [comment]
> @zhiyuanzmj 可能是电池接口松了
更新到最新后 发现不能让电脑自动进入睡眠状态 否则就会关机 解决办法是在节能设置里 设置永不关闭显示器....

**Comment by johnnynunez** [comment]
First of all, update laptop to last bios.
For me, shutdown works well.
Trackpad it is still beta version because voodooi2c not is all compatible with synaptics
