### ISSUE TITLE
m3-7y30 EFI

### ISSUE THREAD

**Issue by sibintb** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#61]
Anyone using Big Sur on m3 7y30 cpu, If yes please share me the EFI
This EFI not working, not even load from usb, stuck at 30%(approximate) while loading from pendrive!

**Comment by johnnynunez** [comment]
This efi is to ice lake m3-6y30

**Comment by atsen-dev** [comment]
I also have a mi notebook air with m3 7y30 cpu, did anyone succeed at install macos on it ? Did it work smoothly ?

Thank in advance

**Comment by johnnynunez** [comment]
you can use it
