### ISSUE TITLE
SSD NVMe problem

### ISSUE THREAD

**Issue by giusedm** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#66]
the last EFI don't recognize SSD in Disk Utility @johnnync13 ?

**Comment by johnnynunez** [comment]
I have to check

**Comment by giusedm** [comment]
Ok please

**Comment by johnnynunez** [comment]
it's problem with bluetooth kext

**Comment by giusedm** [comment]
if remove intelbluetooth injector or add bluetoolfix in boot don't see the Monterey installer 
can you help me @johnnync13
