### ISSUE TITLE
Xiaomi mi air 12.5 (m3_8100y)

### ISSUE THREAD

**Issue by Sharpeacee** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#69]
Hello @johnnync13 . I hope you are  taking care yourself. I have a question for you. I've got a Xiaomi mi air 12.5 laptop wich is has intel m3-8100y CPU. Can i use your EFI folder for booting my system. I know this is for your system and this EFI belongs your system's specification but as you see, my hardwer is really close to yours. I'm wating you advice. Thanks for your time. Best wishes...

**Comment by johnnynunez** [comment]
yes you can, only change model in opencore
