### ISSUE TITLE
Will not disconnect the power after shutdown

### ISSUE THREAD

**Issue by geekcj12** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#7]
The screen has been turned off after shutdown, but the power button is still on.

**Comment by johnnynunez** [comment]
I see soon this problem. Thanks!

**Comment by johnnynunez** [comment]
Now this laptop works perfectly @geekcj12 Use this EFI https://github.com/johnnync13/EFI-Xiaomi-Notebook-air-12-5/releases/tag/v2.8
