### ISSUE TITLE
Needs update to OpenCore

### ISSUE THREAD

**Issue by deadlydag** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#70]
Hi!

Trying to update my Notebook Air again (after a year or so out of the loop),
and it seems like your newest files doesn't boot with the newest OC (0.7.8).
Keeps getting errors from the config.plist

Any chance for an update?

regards from Norway!

**Comment by johnnynunez** [comment]
try the last version. If not, use opencore https://mackie100projects.altervista.org/opencore-configurator/
