### ISSUE TITLE
can't boot using opencore,it's stop on Mi logo

### ISSUE THREAD

**Issue by mic1491** [johnnync13/EFI-Xiaomi-Notebook-air-12-5#71]
Dear Sir.I have Xiami notebook Air 12.5" but it is m3-7y30 type.I install Macos12.5.1 using ur Opencore EFI,but it was stop.So can u help me?

**Comment by johnnynunez** [comment]
> Dear Sir.I have Xiami notebook Air 12.5" but it is m3-7y30 type.I install Macos12.5.1 using ur Opencore EFI,but it was stop.So can u help me?

it's for ventura
